name: nova_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
    
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
    
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

    - family: MajorMonoDisplay
      fonts:
        - asset: assets/fonts/MajorMonoDisplay-Regular.ttf
